apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
  annotations:
    cni.daocloud.io/ipAddrs: 192.168.2.[2-8]
    cni.daocloud.io/currentUser: admin
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Never
